services:
  frontend:
    build: frontend
    restart: unless-stopped
    depends_on:
      - backend

    ports:
      - "8000:8080"

  backend:
    build: backend
    restart: unless-stopped
    depends_on:
      - database

    ports:
      - "8080:8080"

    command:
      - "--repository.storage.path=/var/lib/repos"
      - "--spring.profiles.active=postgres"
      - "--spring.datasource.url=jdbc:postgresql://database:5432/babel"
    volumes:
      - repos:/var/lib/repos:rw


  database:
    image: postgres:18-alpine
    restart: unless-stopped

    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: babel
    volumes:
      - database:/var/lib/postgres:rw

    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 3s
      retries: 3



volumes:
  database:
  repos:
